mingzi_input=input("请输入您的名字: ")
xingbei_input=input("请输入您的性别: ")
nianling_input=input("请输入您的年龄: ")
xuexing_input=input("请输入您的血型: ")
xuexiao_input=input("请输入您的学校: ")
zhuanye_input=input("请输入您的专业: ")
print("正在生成你的简历……")
s1=" "
print(s1)
print('*'*30)
print("  简历")
print( )
print("姓名: "+mingzi_input)
print("性别: "+xingbei_input)
print("年龄: "+nianling_input)
print("血型: "+xuexing_input)
print("学校: "+xuexiao_input)
print("专业: "+zhuanye_input)
