print("Hello~ This is my homework.")
name=input("请输入您的名字: ")
gender=input("请输入您的性别: ")
age=input("请输入您的年龄: ")
school=input("请输入您的学校: ")
print("正在生成您的简历......")
print('*'*30)
print(     简历         )
a=(":")
print("姓名"+a+""+name)
print("性别"+a+""+gender)
print("年龄"+a+""+age)
print("学校"+a+""+school)
print("                ")
print("                ")
print("                ")
print("                ")
print( '''     感谢使用                 '''       )