name=input("\t请输入您的名字: ")
age=input("\t请输入您的年龄: ")
xes=input("\t请输入您的性别: ")
te=input("\t请输入您的特长: ")

print("\t正在生成您的简历......")
print("\t"'*'*30)
print("\t*\t\t\t*")
print("\t*\个人简历\t*")
print("\t*\t\t\t*")
print("\t*\t名字: ",name,"\t*")
print("\t*\t年龄: ",age,"\t*")
print("\t*\t性别: ",xes,"\t*")
print("\t*\t特长: ",te,"\t*")
print("\t*\t\t\t*")
print("\t"'*'*30)